---
- name: Converge
  hosts: all
  tasks:
    - name: Deploy chisel server.
      vars:
        chisel_service_name: chisel-server
        chisel_config_name: chisel-server
      include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"

    - name: Deploy chisel client.
      include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
